hydra:
  run:
    dir: hydra_output/

exp:
  exp_name: test

data:
  load_size: 384
  img_size: 256

train:
  batch_size: 32
  epoch: 10
  seed: 42
  fold: 0
  lr: 0.00005
  model_name: efficientnet-b0
